### PR TITLE
readme: better wording, perhaps prevent #271 #272 happening again

### PR DESCRIPTION
**Pull request by norgeous**
not sure if accurate, but was attempting to increase accuracy of statements around SyncTrayzor Portable version, to prevent confusion in future.

### CODE REVIEW

**Comment by canton7** [comment]
I'm generally in favour, but I don't think that people are going to read this until something goes wrong, and by that point it might be too late.

We should probably implement a better migration story: detect when someone tries to manually convert between the installed and portable versions, and do something sensible. I'm not sure that we should do, though:

 - It's easy to manually convert the `SyncthingPath`, `SyncthingCustomHomePath` and `SyncthingUseCustomHome`. Not a problem.
 - If we do this before allowing Syncthing to start, we could potentially copy Syncthing's config folder over. This could be error-prone, though.
 - We couple simply say "hey, not supported", or direct them to some docs.

**Comment by canton7** [comment]
Right! I've removed the GUI option to use a custom home directly for Syncthing, made the config file so that it can be moved safely between the installed and portable version, and updated the README (https://github.com/canton7/SyncTrayzor/commit/c7b402ef7762fe01e347ac2d0172c28dc884951f). Let me know if there's anything else you think should be changed.

**Comment by norgeous** [comment]
perfect! good work, that looks like it really covers everything.

**Comment by norgeous** [comment]
untitled

**Comment by canton7** [comment]
Bah, thanks.

**Pull request closed without merging**
