### PR TITLE
[Issue-548] Chocolatey package include binaries in package

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**

### CODE REVIEW

**Comment by canton7** [comment]
Perfect, thank you!

**Comment by canton7** [comment]
It looks like this is the wrong thing to do. I just got this email:

User tunisiano <helpdesk.choc@gmail.com> sends the following message to the maintainers of Package 'synctrayzor'.

Hello,
can you update this package ?
The package sent contains the installers, it shouldn't.

Have a nice day.

**Comment by canton7** [comment]
Unfortunately the build for 1.1.27 includes the installers, which means I cannot publish a Chocolatey package for 1.1.27.

**Comment by TheCakeIsNaOH** [comment]
> It looks like this is the wrong thing to do. I just got this email:

He is wrong. Read the "include the software installer" section here:
https://docs.chocolatey.org/en-us/create/create-packages#including-the-software-installer-in-the-package

**Comment by canton7** [comment]
OK, thanks. I'll punt 1.1.27, see what they say

**Comment by TheCakeIsNaOH** [comment]
Whoops, this is kind of awkward, I should have tested this more.

It seems like the .Net install that synctrayzor does is not completely silent, so it is timing out the verifier test waiting for the dotnet install that needs the finish button clicked. 

You could either make the .Net install completely silent, or you could install .Net from Chocolatey as a dependency so it won't be required during the SyncTrayzor install. 

For the depedency, use `<dependency id="dotnetfx" version="4.7.2" />` in the `.nuspec`, right next to the chocolatey depedency.

**Pull request merged**
