### PR TITLE
(#git627) Chocolatey use splatting

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**

### CODE REVIEW

**Comment by canton7** [comment]
That seems to do the trick! Thanks, very elegant.

Are you OK for me to merge this, or does the draft status mean you've got something else up your sleeve?

**Comment by canton7** [comment]
That said, it did log

```
Installing 64-bit SyncTrayzor...
SyncTrayzor has been installed.
ERROR: Cannot bind argument to parameter 'Path' because it is null.
  synctrayzor can be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of synctrayzor was NOT successful
```

The full log file says:

```
2021-03-13 19:06:07,012 19156 [DEBUG] - Running 'ChocolateyScriptRunner' for synctrayzor v1.1.28.620 with packageScript 'C:\ProgramData\chocolatey\lib\synctrayzor\tools\chocolateyinstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\synctrayzor', installArguments: '', packageParameters: '',
2021-03-13 19:06:07,021 19156 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\synctrayzor\tools\chocolateyinstall.ps1'
2021-03-13 19:06:07,101 19156 [DEBUG] - Running Install-ChocolateyInstallPackage -silentArgs '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /SkipDotNetInstall' -file 'C:\ProgramData\chocolatey\lib\synctrayzor\tools\SyncTrayzorSetup-x86.exe' -file64 'C:\ProgramData\chocolatey\lib\synctrayzor\tools\SyncTrayzorSetup-x64.exe' -fileType 'exe' -validExitCodes '0' -packageName 'SyncTrayzor' 
2021-03-13 19:06:07,112 19156 [DEBUG] - Running Get-ProcessorBits -compare '32' 
2021-03-13 19:06:07,145 19156 [INFO ] - Installing 64-bit SyncTrayzor...
2021-03-13 19:06:07,239 19156 [DEBUG] - Running Start-ChocolateyProcessAsAdmin -validExitCodes '0' -workingDirectory 'C:\ProgramData\chocolatey\lib\synctrayzor\tools' -statements '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /SkipDotNetInstall ' -exeToRun 'C:\ProgramData\chocolatey\lib\synctrayzor\tools\SyncTrayzorSetup-x64.exe' 
2021-03-13 19:06:07,242 19156 [DEBUG] - Unable to use current location for Working Directory. Using Cache Location instead.
2021-03-13 19:06:07,269 19156 [DEBUG] - Test-ProcessAdminRights: returning True
2021-03-13 19:06:07,281 19156 [DEBUG] - Elevating permissions and running ["C:\ProgramData\chocolatey\lib\synctrayzor\tools\SyncTrayzorSetup-x64.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /SkipDotNetInstall ]. This may take a while, depending on the statements.
2021-03-13 19:06:24,609 19156 [DEBUG] - Command ["C:\ProgramData\chocolatey\lib\synctrayzor\tools\SyncTrayzorSetup-x64.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /SkipDotNetInstall ] exited with '0'.
2021-03-13 19:06:24,623 19156 [DEBUG] - Finishing 'Start-ChocolateyProcessAsAdmin'
2021-03-13 19:06:24,626 19156 [INFO ] - SyncTrayzor has been installed.
2021-03-13 19:06:24,645 19156 [ERROR] - ERROR: Cannot bind argument to parameter 'Path' because it is null.
2021-03-13 19:06:24,656 19156 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\synctrayzor\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
2021-03-13 19:06:24,660 19156 [DEBUG] - Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
2021-03-13 19:06:24,716 19156 [DEBUG] - Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'
2021-03-13 19:06:24,886 19156 [INFO ] -   synctrayzor can be automatically uninstalled.
2021-03-13 19:06:24,896 19156 [WARN ] - Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
```

**Comment by TheCakeIsNaOH** [comment]
And that is mainly why I had it draft, I wrote and committed before tested it.

I just force pushed this, it should be working now.

**Comment by TheCakeIsNaOH** [comment]
I'm also thinking of perhaps uninstalling the 32 bit version before installing the new 64 bit version?

So when 1.1.29 comes out, 1.1.28 32 bit will be uninstalled? Or is the older 32 bit version just going to be ignored? Or perhaps the inno installer would take care of that?

Just spitballing ideas at the moment.

**Comment by canton7** [comment]
As far as Inno Setup and Windows is concerned, the 64-bit and 32-bit applications are entirely independent. They have separate GUIDs, different names, and live in different places.

I'm not sure how that best ties into chocolatey... If that gets confused by the next upgrade and installs both side-by-side (or if it's already gotten confused since the last upgrade), that's a problem I think.

**Comment by TheCakeIsNaOH** [comment]
> If that gets confused by the next upgrade and installs both side-by-side (or if it's already gotten confused since the last upgrade), that's a problem I think.

Next upgrade (assuming something like this is merged), it should install the 64 bit version, but the 32 bit 1.1.28 would still hang around I think.

I've added another commit, take a look, I think it should fix it.

**Comment by canton7** [comment]
I can't spot any issues with that (the messages could do with a tweak, but that's minor), but the whole approach makes me a bit nervous. Would it perhaps be better to stick with x86 if they previously had x86 installed? Realistically there's no major difference between the two (the x86 version will use slightly less memory), and if they were using 1.1.28 x86 just fine, I'm nervous about forcing them onto x64.

**Comment by TheCakeIsNaOH** [comment]
Well, on 64-bit systems the Chocolatey package has been in previous version installing the 64 version no matter what is currently installed. The only exception is if someone passed the `--forcex86` switch to choco.

So, the only people this should affect:
1. People who mistakenly got the 32 bit version of 1.1.28
2. People who have 64 bit 1.1.24 (or whatever) from Chocolatey, and a non-chocolatey (presumably older) 32 bit version as well.

**Comment by canton7** [comment]
Fair, good points.

I'm still a bit nervous -- with this many users, every decision seems to have side-effects which affect at least a few vocal users -- but I can't think of anything better.

**Comment by TheCakeIsNaOH** [comment]
> with this many users, every decision seems to have side-effects which affect at least a few vocal users

I'd say it has to do more with my lack of testing of #550, as both this and #598 were caused by stuff I forgot/missed there.

**Comment by TheCakeIsNaOH** [comment]
So for testing here is what I have done:
- Upgrading from 1.1.28 works on windows 10 and server 2012 (chocolatey test env)
- Fresh install works on windows 10 and server 2012
- Upgrading from 1.1.24 works on server 2012
- Fresh install with --forcex86 works on server 2012
- Upgrading from 1.1.24 with --forcex86 on both works on server 2012

**Comment by canton7** [comment]
A couple of things I realised overnight:

1. Uninstalling SyncTrayzor attempts to remove all of its config. It's an attempt because it can only affect the current user's files, but that's probably the majority case.
2. Switching from x86 to x64 will also delete the user's auto-start preference.
3. We mess up the version and architecture of the Syncthin binary we use.
4. Uninstallation fails if SyncTrayzor is running

To expand point 3 a bit: SyncTrayzor lets Syncthing auto-upgrade, and it does this by putting a copy somewhere user-writable, in AppData. This means that the version of Syncthing being used by a user can be different to a version included with SyncTrayzor, and that each user on a machine can end up with a different version of Syncthing. Syncthing does not like being downgraded, so we need to be very careful to retain the user's version of Syncthing across upgrades. With this PR, either:

1. We try to delete the user's version of Syncthing on uninstall and succeed (see point 1 above). Now we risk downgrading it.
2. We fail to delete the user's version of Syncthing on uninstall, and now they're left with an x86 Syncthing binary, running under an x64 SyncTrayzor installation. This isn't a problem per se, but it's confusing.

To expand point 4: Inno Setup provides support for gracefully shutting down and restarting the application during installation, which we use during upgrades to make sure that SyncTrayzor isn't running. It doesn't provide the same during uninstallation, which means that it fails to uninstall everything if SyncTrayzor is running. I'm guessing your tests above didn't test this case.

All of that leads me to 1 conclusion: we should detect whether the user has the x86 version of SyncTrayzor installed, and if so upgrade them to the x86 version of SyncTrayzor. If the user wants to switch from x86 to x64, they'll have to uninstall and reinstall, but at least they're prepared for the oddities which might happen (like config being deleted). 

I think this also makes sense for the case where a user has the non-chocolatey x86 version installed, and then does `choco install SyncTrayzor`: we'll upgrade them, rather than installing the two side-by-side.

This won't require an installer update, so we can push out a new chocolatey version soon (although I don't think we can get AppVeyor to create it, annoyingly).

**Comment by TheCakeIsNaOH** [comment]
> All of that leads me to one conclusion: we should detect whether the user has the x86 version of SyncTrayzor installed, and if so upgrade them to the x86 version of SyncTrayzor.

What should happen if both a x64 and x86 version are installed?

**Comment by canton7** [comment]
I think we'd have to fall back on the normal Chocolatey logic of "x86 if the platform is x86 of they pass `--forcex86`, and x64 otherwise. We have no way of knowing which one was originally installed by Chocolatey.

**Comment by TheCakeIsNaOH** [comment]
> I think we'd have to fall back on the normal Chocolatey logic of "x86 if the platform is x86 of they pass --forcex86, and x64 otherwise.

That sounds reasonable.

I updated the second commit, what do you think of this method for checking?

**Comment by canton7** [comment]
I think that's sensible. I'd probably have done something a bit simpler, but this way gives you the opportunity to do more logging, which isn't a bad thing. Thanks!

Is this ready to merge?

**Comment by TheCakeIsNaOH** [comment]
I think this is ready to merge.

**Comment by canton7** [comment]
Thanks! Merged as 181233c2ae33 (I had to rebase it onto develop, and merge it into develop)

**Comment by canton7** [comment]
Actually, I take that back: I undid the merge.

Is there any way to avoid `Get-UninstallRegistryKey` printing this out?

> WARNING: No registry key found based on  'SyncTrayzor (x86)*'

It's a bit ugly and misleading.

**Comment by TheCakeIsNaOH** [comment]
You can assign the result to `$null`.

Like `if (($null = Get-UninstallRegistryKey -SoftwareName 'SyncTrayzor (x86)*')) {`

**Comment by canton7** [comment]
Hmm, that didn't seem to change whether it printed a warning

**Comment by TheCakeIsNaOH** [comment]
Interesting, it does not print that for me.

**Comment by canton7** [comment]
Do you know the x86 or x64 version of SyncTrayzor already installed (or neither)?

**Comment by TheCakeIsNaOH** [comment]
x64 is installed, but not x86

**Comment by canton7** [comment]
Same as me then. Weird. chocolatey version perhaps? Mine's 0.10.15

**Comment by TheCakeIsNaOH** [comment]
That is what I have as well. 

Ah, it might be pulling the function from `chocolatey-core.extension`, which does not have that warning.

**Comment by TheCakeIsNaOH** [comment]
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/extensions/chocolatey-core.extension/extensions/Get-UninstallRegistryKey.ps1

vs

https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-UninstallRegistryKey.ps1

I pretty much universally have that extension installed, so that is why I didn't notice it.

**Comment by TheCakeIsNaOH** [comment]
`Get-UninstallRegistry` key could be replaced by 

`Test-Path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{c9bab27b-d754-4b62-ad8c-3509e1cac15c}_is1"` 

and

`Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{c004dcef-b848-46a5-9c30-4dbf736396fa}_is1"` 

As in this case you are also in controll of where the registry uninstall information goes, so if it changes, you can change it here as well.

**Comment by canton7** [comment]
I ended up copying the implementation from chocolatey.resources, thanks for the tip!

Now there's the slightly odd issue that if the user has x86 and x64 installed side-by-side, the uninstall script complains that it's not going to uninstall anything, and then goes and uninstalls the x86 version anyway!

See the branch pr-628, since I don't have permission to push to your branch.

**Comment by TheCakeIsNaOH** [comment]
> the uninstall script complains that it's not going to uninstall anything, and then goes and uninstalls the x86 version anyway!

That is not the uninstall script, that is the chocolatey automatic uninstaller:
https://docs.chocolatey.org/en-us/choco/commands/uninstall

**Comment by canton7** [comment]
Whatever it is, telling the user we're not touching anything and then uninstalling anyway is bad.

Are we better off getting rid of chocolateyuninstall.ps1 and relying in the auto uninstaller? I don't fully grasp how all the different parts work together, and finding introductory docs is quite hard

**Comment by TheCakeIsNaOH** [comment]
> Are we better off getting rid of chocolateyuninstall.ps1 and relying in the auto uninstaller?

That might be for the best. 

That way, it will only uninstall whatever it captured during the `chocolateyInstall.ps1`

**Comment by canton7** [comment]
Sounds good thanks. I'll try and get that in tomorrow.

**Comment by canton7** [comment]
Almost there... The problem now is that if you:

1. Have x64 installed
2. Install x86
3. Upgrade, so it upgrades x64
4. Uninstall, now it uninstalls x86, and further uninstalls fail because chocolatey no longer thinks you have it installed

Is there any way to ask Chocolatey which version it thinks is installed (i.e. which version the uninstaller is going to uninstall), which we can use as a tie-break if both x86 and x64 are installed?

**Comment by canton7** [comment]
(I've been through the docs and issues list with a fine-toothed comb and can't find anything, so we may just have to live with this, annoyingly. Chocolatey does have the information we need, in its `.chocolatey\synctrayzor.x.y.z\.registry`, but there doesn't seem to be any way of querying this.)

**Comment by TheCakeIsNaOH** [comment]
It is possible to skip the automatic uninstall by way of  a `.skipAutoUninstall` file included in the package, and only run the uninstall script.

I'm not sure that is in the docs.

**Comment by canton7** [comment]
Cool, I can't think of any way to improve the current situation, so I've merged and pushed the package. Let's see if it breaks anyone!

Thanks a lot for your help, as always!

**Pull request closed without merging**
