### PR TITLE
Adding localization support

### PR DESCRIPTION
**Pull request by kreischweide**
The app currently does not support translation. I've looked at msbuildtool/LocBaml and resx based translations and found that the latter is much cleaner and easier to use.

I've translated the AboutView and MainMenu as example.

I've also created an transifex account (syncthing uses the same) for the resx translation part and it worked "okayish" as I do not have any previous experience with it. Might need to create a bash script to download and export the correct files from the platform. If you want I can give you access or transfer the account over to you, if you have one.

Take a look if you have time, maybe this is usefull / correctly implemented (no WPF / translation experience with C# before).

### CODE REVIEW

**Comment by canton7** [comment]
Please open an issue to have a discussion before putting a lot of effort into something like this! I had my own parallel work on this front :) 

Give me a few days to get my act together (and remind myself what I did last time I internationalised a WPF application). I also want to mull over options for switching languages at runtime.

I suspect I'll probably end up with a combination of your resource files (thanks for providing the German translation!) and a custom set of markup extensions.

**Comment by kreischweide** [comment]
Sure, good idea, no time wasted. This was just an experiment to gain some knowledge on how WPF works. Maybe you can use it, otherwise just feel free to drop the PR :)

**Comment by canton7** [comment]
Right! I've got my infrastructure in place, see the [feature/localization](https://github.com/canton7/SyncTrayzor/tree/feature/localization) branch. I took some of your commits and cherry-picked them onto that branch. Let me know if anything I've done doesn't make sense!

I haven't yet had a chance to look into transifex, and how best to integrate that - hopefully I'll have the chance tomorrow. It looks like it's free for open-source projects? In that case I've no inherent objections to using it.

It's probably best to keep the localization branch separate until all strings have been extracted from the UI, then take things from there. I'll hopefully be able to do this in the next few days - thankfully there's not that much to the application!

**Comment by kreischweide** [comment]
Sure, I will take a look tomorrow! Yes, Transifex is free for open-source, you just upload the base Resources.resx and define the languages that you want to work on. Through some CLI tool you can than export the translations in different formats (also resx) and replace the ones in the project, it seems.

**Comment by canton7** [comment]
Would you mind adding me as a maintainer on Transifex? My nick there is canton7 as well (https://www.transifex.com/accounts/profile/canton7/).

I've no objection to you owning the translation effort if you want to - it would be much appreciated! So long as I have the power to keep things rolling if for some reason you disappear.

**Comment by kreischweide** [comment]
I've added you. No problem with the effort, at least on the german side ;-) Just page me if you feel this is the right solution and I will transfer the ownership of the project over to you.

**Comment by canton7** [comment]
Thanks! I'll spend a while playing, working with the API, etc.

**Comment by canton7** [comment]
Do you have permission to delete the 'en_US' and 'de' (not 'de_DE') languages? I can't seem to find a way.

**Comment by kreischweide** [comment]
Yeah, it's somewhat hidden. You need to go to the responsible team of this language and then delete it on the team overview. Check https://www.transifex.com/organization/kreischweide/team/37446/ if you have the options there (lower left).

**Comment by canton7** [comment]
Aah it's hidden until you mouseover! I'd made it to that page, but not moved my mouse into the right place... Thanks!

**Comment by canton7** [comment]
After an initial fight, I'm coming to terms with Transifex - looks neat! Got the command-line tool working (after some headaches), which makes uploading the source / downloading updates really quite trivial.

Currently in the process of extraction all strings. Maybe over half way there?

**Comment by canton7** [comment]
I think that branch is almost done! I still need to add comments, but I think that's all the strings extracted

**Comment by kreischweide** [comment]
Great! I've completed the german translation, though it can be used for "de" as there are not region specific translations required.

**Comment by canton7** [comment]
Thanks so much!

I couldn't find a way to change the de-DE translation to de, so I removed and re-uploaded. Unfortunately that had the consequence of marking me as the translator - this wasn't intentional I promise! I'll sort out my own translation docs and attribution on github soon anyway.

I found out I (or git?) had messed up LF/CRLF in the base resources file, which lead to a few extra newlines in the translation. I've fixed up both sides of that. 

I'm aiming to get this merged in, and the next version out, tomorrow sometime.

**Comment by kreischweide** [comment]
Should be no problem, as we both are in the same team, everyone can become a translator I guess.

**Comment by canton7** [comment]
Bit of a stall on the release since the German strings are overflowing the UI on the Settings screen, and i'm trying to come up with a neat solution.

**Comment by kreischweide** [comment]
Uh, otherwise tell me which strings and I try to reduce the length... a bit.

**Comment by canton7** [comment]
I think the UI needs to be flexible enough to handle a few longer strings, so don't worry.

**Comment by kreischweide** [comment]
Looks perfect so far! I will close the PR.

**Comment by canton7** [comment]
Cool!

I'm going to make a few tweaks this iteration - things like adding a field in the 'about' box to allow translators to give themselves credit - but I'll probably announce those via Transifx.

**Comment by canton7** [comment]
FYI, there's a new key 'TranslatorAttributation' where you can add a little note giving yourself attributation, if you want

**Pull request closed without merging**
