### PR TITLE
Update README to use https in all links

### PR DESCRIPTION
**Pull request by scienmind**
Re-submitting against develop branch

### CODE REVIEW

**Comment by canton7** [comment]
49 commits? Can you rebase onto develop?

**Comment by canton7** [comment]
No need to close - just `git rebase develop && git push -f`

**Comment by canton7** [comment]
Never mind - I grabbed it and rebased it myself.

Thanks!

**Comment by scienmind** [comment]
Turns out I need to set it up locally first, since there is no way to rebase it from github's web-ui that I'm aware of... so I decided to closed the PR until i figure it out. 

Thanks! I'll do it properly next time :)

**Comment by canton7** [comment]
Aah fair enough. No worries.

**Pull request closed without merging**
